FROM python:3.12-slim

WORKDIR /app
COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install debugpy
COPY backend/ ./

EXPOSE 5000 5678

# Executa debugpy e espera a conexão do VS Code antes de rodar app.py
CMD ["python", "-Xfrozen_modules=off", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "app.py"]
